//ISO 3166-1 country names
export const restrictedCountries = [
  'Afghanistan',
  'American Samoa',
  'Anguilla',
  'Antigua and Barbuda',
  'Belarus',
  'Bosnia Herzegovina',
  'Central African Republic',
  'Cuba',
  'DR Congo',
  'Ethiopia',
  'Fiji',
  'Guam',
  'Hong Kong',
  'Iran',
  'Iraq',
  'Kosovo',
  'Lebanon',
  'Libya',
  'Mali',
  'Montenegro',
  'Myanmar',
  'Nicaragua',
  'North Korea',
  'North Macedonia',
  'Palau',
  'Panama',
  'Russia',
  'Samoa',
  'Serbia',
  'Somalia',
  'South Sudan',
  'Sudan',
  'Syria',
  'Ukraine',
  'US Virgin Islands',
  'Vanuatu',
  'Venezuela',
  'Yemen',
  'United States',
  'United Kingdom',
];
