const Routes = {
  Home: "/",
  Create: "/create",
  CreateProfile: "/create/profile",
  CreateProject: "/create/project",
  CreateTeam: "/create/team",
  AllProjects: "/projects/all",
  Projects: "/projects",
  AllQFProjects: "/qf/all",
  QFProjects: "/qf",
  QFArchived: "/qf-archive",
  Project: "/project",
  Success: "/success",
  ReFiProjects: "/projects/finance",
  Donate: `/donate`,
  User: `/user`,
  AboutUs: "/about",
  Faq: "/faq",
  Support: "/support",
  Join: "/join",
  Terms: "/tos",
  Partnerships: "/partnerships",
  Onboard: "/onboard",
  Onboarding: "/onboarding",
  OnboardingProjects: "/onboarding/projects",
  OnboardingDonors: "/onboarding/donors",
};
export default Routes;
