// This is the layout file that works as a Server Component
import { Nunito_Sans } from 'next/font/google';
import './globals.css';
import { cookieToInitialState } from 'wagmi';
import { headers } from 'next/headers';
import Web3ModalProvider from '@/context/wagmi';
import { wagmiConfig } from '@/config/wagmi';
import { Footer } from '@/components/Footer';
import { UserController } from '@/components/Controllers/UserController';
import type { Metadata } from 'next';
import ClientLayout from './ClientLayout'; // Import the client-side layout

const nunito = Nunito_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get('cookie'),
  );

  return (
    <html lang='en'>
      <body className={nunito.className}>
        <div className='min-h-screen flex flex-col relative overflow-x-hidden'>
          <ClientLayout initialState={initialState}>{children}</ClientLayout>
        </div>
      </body>
    </html>
  );
}
